public class arun {

    public static void main(String[] args) {

        System.out.print("SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST\n" +
                "TSETNOCGNIMMARGORPECNEICSRETUPMOCLIUETATS\n" +
                "SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS\n" +
                "STATEUILCOMPUTERSCIENCEPROGRAMMINGCONTEST");

    }

}
